language: c
compiler: gcc
os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
      valgrind
      devscripts
      fakeroot
      debhelper
before-install:
- sudo add-apt-repository ppa:ondrej/debhelper
- sudo apt-get -qq update
script: make all runtests
